WUNDERLIST_TELEGRAM/todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('update/<int:pk>/', views.update, name='update'),    
    path('delete/<int:pk>/', views.delete, name='delete'),

]

WUNDERLIST_TELEGRAM/wunderlist/urls.py
from django.contrib import admin
from django.urls import path, include
from decouple import config
from todos import views

token = config('TELEGRAM_TOKEN2')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
    path(f'{token}/', views.telegram),
]

WUNDERLIST_TELEGRAM/todos/models.py
from django.db import models

# Create your models here.

class Todo(models.Model):
    title = models.CharField(max_length=100)
    due_date = models.DateField()

WUNDERLIST_TELEGRAM/todos/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.views.decorators.csrf import csrf_exempt
import json
from pprint import pprint as pp
from .models import Todo
import requests
from decouple import config

token1 = config('TELEGRAM_TOKEN1')
token2 = config('TELEGRAM_TOKEN2')


# Create your views here.


def index(request):
    todos = Todo.objects.all()
    context = {
        'todos': todos
    }
    return render(request, 'todos/index.html', context)


def create(request):
    # data 가져오기
    if request.method == 'POST':
        title = request.POST.get('title')
        due_date = request.POST.get('due-date')

        Todo.objects.create(title=title, due_date=due_date)
        
        url1 = "https://api.telegram.org/bot" + token1 + "/getUpdates"
        url2 = "https://api.telegram.org/bot" + token2 + "/getUpdates"
        res1 = requests.get(url1)
        res2 = requests.get(url2)
        dict_result1 = res1.json()
        dict_result2 = res2.json()
        chat_id1 = dict_result1["result"][0]["message"]["from"]["id"]
        chat_id2 = dict_result2["result"][0]["message"]["from"]["id"]
        
        base = "https://api.telegram.org/"
        method = "/sendMessage"
        text = "새로운 todo가 생성되었습니다."
        url1 = base + "bot" + token1 + method + "?" + "text=" + text + "&chat_id=" + chat_id1
        url2 = base + "bot" + token2 + method + "?" + "text=" + text + "&chat_id=" + chat_id2
        requests.get(url1)
        requests.get(url2)

        return redirect('todos:index')
    else:
        return render(request, 'todos/create.html')

def update(request, pk):
    todo = get_object_or_404(Todo, id=pk)


    if request.method == 'POST':
        # 갱신된 최신 data 가져오기
        title = request.POST.get('title')
        due_date = request.POST.get('due-date')
        todo.title = title
        todo.due_date = due_date
        todo.save()

        return redirect('todos:index')
    else:
        # 기존 data 가져오기
        context = {
        'todo': todo
        }

        return render(request, 'todos/update.html',context)


def delete(request,pk):
    todo = get_object_or_404(Todo, id=pk)
    todo.delete()
    return redirect('todos:index')

@csrf_exempt
def telegram(request):
    print(request.method)
    res = json.loads(request.body)

    text = res.get('message').get('text')
    chat_id = res.get('message').get('chat').get('id')
    base = 'https://api.telegram.org'
    url = f'{base}/bot{token2}/sendMessage?text={text}&chat_id={chat_id}'
    requests.get(url)
    return HttpResponse('아무메세지')

WUNDERLIST_TELEGRAM/todos/templates/todos/_footer.html
<footer class='bg-success fixed-bottom'>
    <div class="row" style="justify-content:space-around; line-height: 50px">
      <span style="color: aliceblue">ⓒ2019,Kahn & YJK </span>
      <span><a href="#Top_page"><button class="btn btn-light">Top</button></a></span>
    </div>
</footer>

WUNDERLIST_TELEGRAM/todos/templates/todos/_jumbotron.html
<div class="jumbotron jumbotron-fluid d-flex" id="Top_page">
    <div class="container text-center">
      <h1 class="display-4">짭WUNDERLIST를 만들어보자</h1>
    </div>
</div>

WUNDERLIST_TELEGRAM/todos/templates/todos/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'todos:index' %}">WUNDERLIST 콜라보</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'todos:create' %}">스케줄 추가</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">스케줄 리스트</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Login</a>
      </li>
    </ul>
  </div>
</nav>

WUNDERLIST_TELEGRAM/todos/templates/todos/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Jua|Sunflower:300&display=swap" rel="stylesheet">
  <title>WUNDERLIST 콜라보</title>
</head>

<body>
  {% include 'todos/_nav.html' %}
  {% include 'todos/_jumbotron.html' %}

  {% block body %}

  {% endblock %}

  {% include 'todos/_footer.html' %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
</body>

<style>
  * {
  font-family: 'Jua', sans-serif !important;
}
.jumbotron {
  background-image: url('https://static1.visitestonia.com/images/2890339/Estonian_forest_reasons_to_visit_Sven_Zacek.jpg') !important;
  background-position-y: 300px;
}

h1 {
  color: aliceblue;
}

</style>

</html>

WUNDERLIST_TELEGRAM/todos/templates/todos/create.html
{% extends 'todos/base.html' %}
{% block body %}
<div class="container">
    <h2>오늘 할 일 무엇무엇??</h2>
    <div>
      <form action="{% url 'todos:create' %}" method="post">
        {% csrf_token %}
        <input type="text" name="title" placeholder="할 일을 적어주세요">
        <input type="date" name="due-date">
        <input type="submit">
      </form>
    </div>
    <a class="btn btn-dark" href="{% url 'todos:index' %}">스케줄 리스트</a>
</div>

    {% endblock %}

WUNDERLIST_TELEGRAM/todos/templates/todos/index.html
{% extends 'todos/base.html' %}

{% block body %}
<div class="container">
  <div class="row">
    <h2>Kahn & YJK의 짭 WUNDERLIST</h2>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">번호</th>
          <th scope="col">스케줄</th>
          <th scope="col">마감일</th>
          <th scope="col">일정편집/삭제</th>
        </tr>
      </thead>
      <tbody>
        {% for todo in todos %}
        <tr>
          <th scope="row">{{ todo.id }}</th>
          <td>{{ todo.title }}</td>
          <td>{{ todo.due_date }}</td>
          <td><a class="btn btn-info" href="{% url 'todos:update' todo.id %}">수정</a> <button type="button" class="btn btn-danger"
              data-toggle="modal" data-target="#delete">삭제</button></td>
          <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">삭제 가즈아~!</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  정말 삭제할꼬야?
                </div>
                <div class="modal-footer">
                  <a href="{% url 'todos:delete' todo.id %}" class="btn btn-danger">삭제</a>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>

        </tr>
        {% endfor %}
      </tbody>

    </table>
    <a class="btn btn-secondary" href="{% url 'todos:create' %}">스케줄 추가</a>
  </div>
</div>
{% endblock %}

WUNDERLIST_TELEGRAM/todos/templates/todos/update.html
{% extends 'todos/base.html' %}
{% block body %}
<div class="container">
  <h2>김병장님, 일정 편집 하십쇼</h2>
  <form action="{% url 'todos:update' todo.id %}" method="post">
    {% csrf_token %}
    <input type="text" name="title" value="{{ todo.title }}" placeholder="할 일을 적어주세요">
    <input type="date" name="due-date" value="{{ todo.due_date|date:'Y-m-d' }}">
    <input type="submit">
  </form>
</div>

{% endblock %}