BOARD2/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('detail/<int:pk>/', views.detail, name = 'detail'),
    path('create/', views.create, name = 'create'),
    path('update/<int:pk>/', views.update, name = 'update'),
    path('delete/<int:pk>/', views.delete, name = 'delete'),
]

BOARD2/posts/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image_url = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

BOARD2/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .models import Post
import requests
# Create your views here.

def index(request):
    posts = Post.objects.all()
    context = {
        'posts': reversed(posts)
    }
    return render(request, 'posts/index.html', context)

def detail(request,pk):
    posts = Post.objects.get(pk=pk)
    context = {
        'posts': posts
    }
    return render(request, 'posts/detail.html', context)

def create(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        Post.objects.create(title=title, content=content)
        return redirect('posts:index')
    else:
        return render(request, 'posts/create.html')

def update(request,pk):
    posts = Post.objects.get(pk=pk)

    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        posts.title = title
        posts.content = content
        posts.save()
        return redirect('posts:detail',pk)
    else:
        context = {
            'posts': posts

        }

        return render(request, 'posts/update.html', context)

def delete(request,pk):
    posts = Post.objects.get(pk=pk)
    posts.delete()
    return redirect('posts:index')

BOARD2/posts/templates/posts/create.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
  <h2>SSAFY 서울 1반 게시판</h2>
  <div>
    <form action="{% url 'posts:create' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="title" placeholder="할 일을 적어주세요">
      <input type="text" name="content" placeholder="내용을 적어주세요">
      <input type="submit">
    </form>
  </div>
  <a class="btn btn-dark" href="{% url 'posts:index' %}">목록</a>
</div>

{% endblock %}

BOARD2/posts/templates/posts/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
  <h2>SSAFY 서울 1반 게시판</h2>
  <a href="/posts/update/{{ posts.id }}/" class="btn btn-success">수정</a>
  <a href="/posts/delete/{{ posts.id }}/" class="btn btn-danger">삭제</a>
  <h1>{{ posts.title }}</h1>
  <p>{{ posts.content }}</p>
  <img src="{{ posts.image_url }}" alt="">
  <p>{{ posts.created_at }}</p>
  <p>{{ posts.updated_at }}</p>
</div>
{% endblock %}

BOARD2/posts/templates/posts/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
  <div class="row">
    <h1>SSAFY 서울 1반 게시판</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">글번호</th>
          <th scope="col">제목</th>
          <th scope="col">생성일</th>
          <th scope="col">수정일</th>
        </tr>
      </thead>
      <tbody>
        {% for post in posts %}
        <tr>
          <th scope="row">{{ post.id }}</th>
          <td><a href="/posts/detail/{{ post.id }}/">{{ post.title }}</a></td>
          <td>{{ post.created_at }}</td>
          <td>{{ post.updated_at }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

BOARD2/posts/templates/posts/update.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
  <h2>SSAFY 서울 1반 게시판 편집 페이지</h2>
  <form action="{% url 'posts:update' todo.id %}" method="GET">
    <input type="text" name="title" value="{{ posts.title }}">
    <input type="text" name="content" value="{{ posts.content }}">
    <input type="submit">
  </form>
</div>

{% endblock %}