RECAP_Movie/PJT06/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as accounts_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movie.urls')),
    path('accounts/', include('accounts.urls')),
    path('<username>/', accounts_views.profile, name='profile'),
]

RECAP_Movie/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns =[
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name="change_password"),
    path('follow/<int:person_pk>/', views.follow, name="follow"),
]

RECAP_Movie/movie/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/update', views.update, name='update'),
    path('<int:movie_pk>/delete', views.delete, name='delete'),
    path('<int:movie_pk>/create_review', views.create_review, name='create_review'),
    path('<int:movie_pk>/like/', views.like, name="like"),
    path('<int:movie_pk>/dislike', views.dislike, name="dislike"),
    path('send_cookie/', views.send_cookie, name='send'),

]

RECAP_Movie/PJT06/templates/_jumbotron.html
{% load bootstrap4 %}

<div class="jumbotron jumbotron-fluid d-flex" id="Top_page">
  <div class="container text-center">
    <h2 class="display-4">Kahn의 영화페이지</h2>
  </div>
</div>

RECAP_Movie/PJT06/templates/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/movies/">Project06</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'movies:create' %}">영화 정보 생성</a>
          {% endif %}
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">아무의미없는링크</a>
        </li>
      </ul>
    </div>
  </nav>

RECAP_Movie/PJT06/templates/base.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load staticfiles %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://fonts.googleapis.com/css?family=Jua|Sunflower:300&display=swap" rel="stylesheet">
  
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  
  <title>SSAFY Project06</title>
  <style>
    * {
      font-family: 'Jua', sans-serif;
    }

    nav.navbar {
      font-family: 'Sunflower', sans-serif;
    }

    div.jumbotron {
      background-image: url("{% static 'movie-918655_1920.jpg' %}");
      background-position-y: 300px;
    }

    h2 {
      color: aliceblue;
    }

    span {
      color: darkslateblue;
    }
  </style>
</head>

<body>
  {% if user.is_authenticated %}
    <p>안녕하세요, {{ user.username }}님</p>
    <a href="{% url 'accounts:logout' %}">로그아웃</a>
    <a class="btn btn-success" href="{% url 'accounts:update' %}">회원정보수정</a>
    <form style="display: inline;" action="{% url 'accounts:delete' %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="회원탈퇴" class="btn btn-danger">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">로그인</a>
    <a href="{% url 'accounts:signup' %}">회원가입</a>
  {% endif %}
  
  {% include '_nav.html' %}
  {% include '_jumbotron.html' %}
  <div class="container">

    {% block body %}
    {% endblock %}
  </div>
</body>

</html>